type User @table {
  displayName: String!
  email: String!
  userType: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Class @table {
  educator: User!
  name: String!
  courseCode: String!
  description: String!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  scheduleDetails: String
}

type Enrollment @table(key: ["student", "class"]) {
  student: User!
  class: Class!
  enrollmentDate: Date!
  createdAt: Timestamp!
}

type Session @table {
  class: Class!
  sessionDate: Date!
  startTime: String!
  endTime: String!
  createdAt: Timestamp!
  topicCovered: String
  location: String
}

type Attendance @table(key: ["enrollment", "session"]) {
  enrollment: Enrollment!
  session: Session!
  status: String!
  createdAt: Timestamp!
  notes: String
}

type Material @table {
  class: Class!
  uploader: User!
  title: String!
  fileUrl: String!
  fileType: String!
  uploadDate: Date!
  description: String
}